required_files = [
    "requirements.txt"
]
search_parents = false

[before_run]
command = "python -m venv venv && venv/bin/pip install -r requirements.txt"
# Or
# script_path = "before_run.sh"

[run]
subcommand_of = "doit"
# Or
# ends with /, therefore use original executable name appended to path
# path = "venv/bin/"
# Or
# full executable path
# path = "venv/bin/fontbakery"

[fallback]
# Can be omitted to use the next entry in $PATH (excluding the get-it-going executable)
path = "/usr/sbin/fontbakery"
